name: Ebiten
description: Installs Ebiten dependencies for Ubuntu.

runs:
  using: composite
  steps:
    - name: Install Ebiten dependencies.
      run: |
        sudo apt update
        sudo apt install -y \
          libx11-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libxxf86vm-dev
      shell: bash
